sudo: true

language: node_js

branches:
  only:
    - master

node_js:
  - "8"
  - "9"

os:
  - linux

before_install:
 - sudo apt-get install libtool automake autoconf nasm

script: npm run travis:test

